import type { Metadata } from "next";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { AptosWalletAdapterProvider } from "@aptos-labs/wallet-adapter-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <AptosWalletAdapterProvider autoConnect={true}>
            <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%" appearance="dark">
              {children}
            </Theme>
          </AptosWalletAdapterProvider>
        </body>
    </html>
  );
}
